name: CI for Neophrase Plugin

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4  # Specify your Ruby version here
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Tests
        env:
          GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
        run: |
          bundle exec rspec

      - name: Lint with RuboCop
        run: |
          bundle exec rubocop
